### ISSUE TITLE
Part 1 testing

### ISSUE THREAD

**Issue by lrbridge** [lrbridge/mp1#2]
Part 1 is implemented, but maybe we should each take one of the four larger sample mazes and see if the solution looks right for each of the 4 algorithms?

I've gone through many of the smaller mazes and they seem to be right, but I've never gone through the solutions on these mazes:
- mediumMaze.txt
- bigMaze.txt
- openMaze.txt

Sound worthwhile?  Does anyone want to sign up for testing one of those mazes?

**Comment by GoingtoRock** [comment]
If you haven't worked on those, I will try them now.

**Comment by GoingtoRock** [comment]
Done.
